image: docker:latest

services:
  - docker:dind

stages:
  - test

shakti-test:
  stage: test
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build . -t shakti:local
    - docker rm -f shakti || true
    - docker run -p 3030:3030 --name "shakti" -d shakti:local dashing start
    - docker exec -i shakti dashing start
    - docker exec -i shakti curl -I http://localhost:3030/sample
#    - docker exec -i shakti curl -I http://localhost:3030/sample 2>/dev/null | head -n 1 | cut -d$' ' -f2
#    - stats="$(docker exec -i shakti curl -I http://localhost:3030/sample 2>/dev/null | head -n 1 | cut -d$' ' -f2)"
#    - if [ "$(stats)" != "200" ]; then exit 1; else; echo "Dashing is running" exit 0; fi
