image: docker:latest

services:
  - docker:dind

stages:
  - test

shakti-test:
  stage: test
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build . -t shakti:local
    - docker run -i registry.naspersclassifieds.com/panamera/shakti:local dashing start
