image: docker:latest

services:
  - docker:dind

stages:
  - test

shakti-test:
  stage: test
  script:
    - cd dashboard
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker run -i registry.naspersclassifieds.com/panamera/shakti:latest dashing start
