image: docker:latest

services:
  - docker:dind

stages:
  - test
  - deploy

shakti-test:
  stage: test
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build . -t shakti:local
    - docker rm -f shakti || true
    - docker run -p 3030:3030 --name "shakti" -d shakti:local dashing start
    - docker exec -i shakti dashing start
    - docker exec -i shakti curl -I http://localhost:3030/sample
    - docker tag shakti:local registry.naspersclassifieds.com/panamera/shakti:deploy
    - docker push registry.naspersclassifieds.com/panamera/shakti:deploy
#    - docker exec -i shakti curl -I http://localhost:3030/sample 2>/dev/null | head -n 1 | cut -d$' ' -f2
#    - stats="$(docker exec -i shakti curl -I http://localhost:3030/sample 2>/dev/null | head -n 1 | cut -d$' ' -f2)"
#    - if [ "$(stats)" != "200" ]; then exit 1; else; echo "Dashing is running" exit 0; fi

openshift-deploy_staging:
  stage: deploy
  image: registry.naspersclassifieds.com/library/docker/deploy-openshift:latest
  script:
    - oc login --token=${OPENSHIFT_TOKEN} --server=${OPENSHIFT_SERVER} -n dashing --insecure-skip-tls-verify
    - make deploy-common OC_ARGS="--token=${OPENSHIFT_TOKEN} --server=${OPENSHIFT_SERVER} -n dashing" APP=dashing
  environment:
    name: production
  only:
   - develop
