image: docker:latest

services:
  - docker:dind

stages:
  - test

shakti-test:
  stage: test
  script:
    - cd dashboard
    - docker run -i registry.naspersclassifieds.com/panamera/shakti:latest dashing start
