image: docker:latest

services:
  - docker:dind

stages:
  - test

shakti-test:
  stage: test
  script:
    - docker run -i ruby gem install dashing
    - cd dashboard
    - docker run -i ruby dashing start
